export const LOCAL_STORAGE_CART =       'CARTS'
export const LOCAL_STORAGE_PRODUCT =    'PRODUCTS'
export const ADD_TO_CARD        =       'ADD_TO_CART'
export const CHANGE_MESSAGE     =       'CHANGE_MESSAGE'
export const DELETE_CART        =       'DELETE_CART'
export const UPDATE_CART        =       'UPDATE_CART'